// +build windows

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package ecscni

import (
	"fmt"
	"net"

	"github.com/containernetworking/cni/pkg/types"

	"github.com/aws/amazon-ecs-agent/agent/api/eni"
	"github.com/containernetworking/cni/libcni"
	"github.com/pkg/errors"
)

// NewBridgeNetworkConfigForTaskNSSetup is used to create the bridge configuration for task namespace setup
func NewBridgeNetworkConfigForTaskNSSetup(eni *eni.ENI, cfg *Config) (*libcni.NetworkConfig, error) {

	VPCCIDRs := convertIPNetToString(cfg.AllIPV4VPCCIDRBlocks)

	dns := types.DNS{
		Nameservers: eni.DomainNameServers,
	}
	if len(eni.DomainNameServers) == 0 {
		constructedDNS, err := constructDNSFromVPCCIDR(cfg.PrimaryIPV4VPCCIDR.IP)
		if err != nil {
			return nil, errors.Wrapf(err, "cannot create bridge network config")
		}
		dns.Nameservers = constructedDNS
	}

	eniSecondaryIPAddr := ""
	for _, addr := range eni.IPV4Addresses {
		if !addr.Primary {
			eniSecondaryIPAddr = fmt.Sprintf("%s/%s", addr.Address, eni.GetIPv4SubnetPrefixLength())
		}
	}

	if eniSecondaryIPAddr == "" {
		return nil, errors.Errorf("secondary ip address not available for eni with mac: %s", eni.MacAddress)
	}

	eniConf := BridgeForTaskENIConfig{
		Type:             ECSVPCSharedENIPluginName,
		VPCCIDRs:         VPCCIDRs,
		ENIIPAddress:     eni.GetPrimaryIPv4AddressWithPrefixLength(),
		ENIMACAddress:    eni.MacAddress,
		GatewayIPAddress: eni.GetSubnetGatewayIPv4Address(),
		IPAddress:        eniSecondaryIPAddr,
		TaskENIConfig: TaskENIConfig{
			NoInfra:          false,
			EnableTaskENI:    true,
			EnableTaskBridge: false,
		},
		DNS: dns,
	}

	networkConfig, err := newNetworkConfig(eniConf, ECSVPCSharedENIPluginExecutable, cfg.MinSupportedCNIVersion)
	if err != nil {
		return nil, errors.Wrap(err, "cni config: failed to create bridge plugin configuration for setting up task network namespace")
	}

	// Network.Name is used to create the name of the task bridge network.
	// The bridge name generated by the plugin would be of format taskbr<ENI MAC Address>
	networkConfig.Network.Name = TaskENIBridgeNetworkPrefix

	return networkConfig, nil
}

// NewBridgeNetworkConfigForTaskBridgeSetup is used to create the configuration for task bridge setup
func NewBridgeNetworkConfigForTaskBridgeSetup(cfg *Config) (*libcni.NetworkConfig, error) {

	VPCCIDRs := convertIPNetToString(cfg.AllIPV4VPCCIDRBlocks)

	eniConf := BridgeForTaskENIConfig{
		Type:     ECSVPCSharedENIPluginName,
		VPCCIDRs: VPCCIDRs,
		ENIName:  TaskENIBridgeNetworkPrefix,
		TaskENIConfig: TaskENIConfig{
			NoInfra:          false,
			EnableTaskENI:    false,
			EnableTaskBridge: true,
		},
	}

	networkConfig, err := newNetworkConfig(eniConf, ECSVPCSharedENIPluginExecutable, cfg.MinSupportedCNIVersion)
	if err != nil {
		return nil, errors.Wrap(err, "cni config: failed to create bridge plugin configuration for setting up task network namespace")
	}

	// Network.Name is the nat network to which we want to connect our task
	networkConfig.Network.Name = DefaultECSBridgeNetworkName

	return networkConfig, nil
}

// constructDNSFromVPCCIDR is used to construct DNS server from the primary ipv4 cidr
func constructDNSFromVPCCIDR(primaryCIDR net.IP) ([]string, error) {
	// The DNS server maps to a reserved IP address at the base of the VPC IPv4 network rage plus 2
	// https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS
	// Therefore, we construct the same by replacing the last token of the primary cidr to 2

	mask := net.CIDRMask(24, 32)
	maskedIPv4 := primaryCIDR.Mask(mask).To4()
	maskedIPv4[3] = 2

	return []string{maskedIPv4.String()}, nil
}

// convertIPNetToString converts an array of net.IPNet into an array of string representation
func convertIPNetToString(cidr []*net.IPNet) []string {
	parsed := make([]string, len(cidr))

	for index, ipAddr := range cidr {
		parsed[index] = ipAddr.String()
	}

	return parsed
}
